START TRANSACTION;

-- reel_performance_snapshots
CREATE TABLE IF NOT EXISTS reel_performance_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    post_id VARCHAR(128) NOT NULL,
    source_run_id VARCHAR(64) NULL,
    content_version_id BIGINT UNSIGNED NULL,
    snapshot_at DATETIME NOT NULL,
    impressions INT UNSIGNED NOT NULL DEFAULT 0,
    comments INT UNSIGNED NOT NULL DEFAULT 0,
    shares INT UNSIGNED NOT NULL DEFAULT 0,
    video_length_seconds INT UNSIGNED NOT NULL DEFAULT 15,
    total_watch_time_seconds DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    avg_watch_time_seconds DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    three_second_views INT UNSIGNED NOT NULL DEFAULT 0,
    comment_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    hold_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    share_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    data_source VARCHAR(32) NOT NULL DEFAULT 'graph_api',
    fetch_status VARCHAR(32) NOT NULL DEFAULT 'fetched',
    raw_payload JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_post_snapshot (post_id, snapshot_at),
    KEY idx_post_id (post_id),
    KEY idx_snapshot_at (snapshot_at),
    KEY idx_source_run_id (source_run_id),
    KEY idx_content_version_id (content_version_id),
    KEY idx_fetch_status (fetch_status)
);

-- optimizer_queue
CREATE TABLE IF NOT EXISTS optimizer_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    post_id VARCHAR(128) NOT NULL,
    source_run_id VARCHAR(64) NULL,
    content_version_id BIGINT UNSIGNED NULL,
    trigger_snapshot_id BIGINT UNSIGNED NULL,
    optimization_reason VARCHAR(128) NOT NULL,
    metric_trigger VARCHAR(128) NOT NULL,
    original_hook TEXT NULL,
    optimized_hook TEXT NULL,
    original_caption TEXT NULL,
    optimized_caption TEXT NULL,
    original_comment_cta TEXT NULL,
    optimized_comment_cta TEXT NULL,
    version_number INT UNSIGNED NOT NULL DEFAULT 1,
    revenue_score_before DECIMAL(8,4) NULL,
    revenue_score_after DECIMAL(8,4) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    processed_at DATETIME NULL,
    published_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_post_id (post_id),
    KEY idx_source_run_id (source_run_id),
    KEY idx_content_version_id (content_version_id),
    KEY idx_status (status),
    KEY idx_created_at (created_at),
    KEY idx_trigger_snapshot_id (trigger_snapshot_id)
);

-- boost_queue
CREATE TABLE IF NOT EXISTS boost_queue (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    post_id VARCHAR(128) NOT NULL,
    source_run_id VARCHAR(64) NULL,
    content_version_id BIGINT UNSIGNED NULL,
    trigger_snapshot_id BIGINT UNSIGNED NULL,
    decision_source VARCHAR(32) NOT NULL DEFAULT 'revenue_predictor',
    revenue_score DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    comment_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    hold_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    share_rate DECIMAL(10,5) NOT NULL DEFAULT 0.00000,
    boost_priority VARCHAR(16) NOT NULL DEFAULT 'normal',
    status VARCHAR(32) NOT NULL DEFAULT 'queued',
    boost_platform VARCHAR(32) NOT NULL DEFAULT 'facebook',
    campaign_id VARCHAR(128) NULL,
    adset_id VARCHAR(128) NULL,
    ad_id VARCHAR(128) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    processed_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_post_id (post_id),
    KEY idx_source_run_id (source_run_id),
    KEY idx_content_version_id (content_version_id),
    KEY idx_status (status),
    KEY idx_created_at (created_at),
    KEY idx_revenue_score (revenue_score),
    KEY idx_trigger_snapshot_id (trigger_snapshot_id)
);

COMMIT;
